### ISSUE TITLE
Vocabulary

### ISSUE THREAD

**Issue by antoyang** [MILVLG/activitynet-qa#10]
Hi,
It is written in your AAAI paper "To generate the answer vocabulary, we choose the top 1,000 most frequent answers in the train split as the answer vocabulary, which covers 84.7% / 86.2% / 85.6% of the train/val/test answers, respectively".
However, choosing the same vocabulary, I obtain significantly lower coverage ( about 78% for test and 80% for val). Do you have an idea why? Do you process further the answers?

Best,
Antoine Yang

**Comment by datar001** [comment]
Same questions. I got 84.7% / 82.2% / 78.6% for the train/val/test answers. Did you find the reason? Thx.
![微信截图_20210701110508](https://user-images.githubusercontent.com/62345916/124058600-41c1d300-da5c-11eb-8b86-3b9ea2c4bd28.png)
