### ISSUE TITLE
Question types

### ISSUE THREAD

**Issue by YuliaNovskaya** [MILVLG/activitynet-qa#9]
Where I can find the question types? 
train_q.json doesn't have this field
train_a.json has this field, but it is related to the answer types, not to question.

In readme mentioned: 
The answer field contains the answer with respect to the question with question_id The type file contains the question or answer types for this question:
Question types: [0].Motion [1].Spatial Relationship [2].Temporal Relationship [3-8].Free

However, I can't find neither a 'type' file nor a 'type' field, related to the question
Thanks in advance

**Comment by MIL-VLG** [comment]
All types (question type and answer type) are stored in the *_a.json file, with [0-2] corresponding to the question types, while [3-8] to the answer types.

**Comment by YuliaNovskaya** [comment]
Thank you
